jobs:
- name: test
  public: true
  plan:
  - get: lua-toolbox
    trigger: true
  - in_parallel:
    - task: check
      config:
        inputs:
        - name: lua-toolbox
        platform: linux
        image_resource:
          type: registry-image
          source: {repository: booleancat/lua-toolbox-ci}
        run:
          dir: lua-toolbox
          path: sh
          args:
          - -exc
          - make check
    - task: test
      config:
        inputs:
        - name: lua-toolbox
        platform: linux
        image_resource:
          type: registry-image
          source: {repository: booleancat/lua-toolbox-ci}
        run:
          dir: lua-toolbox
          path: sh
          args:
          - -exc
          - make build; make test

resources:
- name: lua-toolbox
  type: git
  icon: git
  source:
    uri: https://github.com/BooleanCat/lua-toolbox.git
